### ISSUE TITLE
Wrong class displayed. Yikes!

### ISSUE THREAD

**Issue by il-ydna** [GunnWATT/watt#11]
Hello fellow Gunn Watt Contributors,

The Gunn Admins decided to flip flop GT and SELF on a weekly basis. We should make sure our website reflects this change

**Comment by SheepTester** [comment]
Allow me to present you with two solutions:

UGWA uses its antiquated SELF detection from previous years to use the SELF/GT events helpfully provided in the school calendar to automatically determine whether GT and SELF have been flipped

Homework Central uses its fanciest Firebase backend to have a schedule editor and manually update the schedule as needed

**Comment by ky28059** [comment]
Seems like 
```js
// Support Gunn's swapping of GT and SELF every other week
if (viewDate.isAfter('4/11/2021')) {
    let offset = viewDate.weeks() % 2;
    if (offset === 0) {
        if (name === 'G') name = 'S';
        else if (name === 'S') name = 'G';
    }
}
```
will have to do
