### ISSUE TITLE
Repurpose link field in `/settings/periods` for room numbers

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#116]
This would make `PeriodObj` something like
```ts
{n: string, c: string, l: string, o: string, s: string, r: string}
```
with `l` being deprecated and unused. Instead of rendering links, we would render a room number next to the period name in the same style as how we currently handle grade numbers. Unsure if these are fetchable via schoology, but if not manual is always fine as well.

**Comment by MysticalApple** [comment]
PR #118 should do this, although it doesn't display room numbers in exactly the same way that grade numbers are displayed. (example attached)
![image](https://user-images.githubusercontent.com/81409252/184329775-4bcbec73-57d1-43af-8c94-f97901d34080.png)
