### ISSUE TITLE
Responsive design bugs on small screens (phones)

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#13]
- [x] certain no school images will appear clipped because their max height and max width are set statically
- [ ] the nav tabs of /utilities and /settings stack on top of each other due to tab text not fitting in one line
- [x] the Wednesday h1 in schedule clips off the side of the screen as it is too wide
- [x] the bottom nav's `position: absolute` makes the bottom part of the screen inaccessible
- [x] the search bar in /clubs clips out of the header when it is too small to fit
- [x] event header stickyness on mobile causes text overlap
- [x] bootstrap modals are non scrollable, causing certain clubs to have parts of their modal inaccessible
- [x] the use of 100vh on body and flexbox to position the bottom nav causes it to be obscured on mobile browsers when the stupid top thing is open

Also, for consideration:
- [x] Bizarre white stripes on old phones (most likely from expensive painting)

**Comment by ky28059** [comment]
Clipped Wednesday
<img width="303" alt="1" src="https://user-images.githubusercontent.com/60120929/116958544-e2a83380-ac4f-11eb-8a46-441006b2698c.png">
Stacked tabs
<img width="292" alt="2" src="https://user-images.githubusercontent.com/60120929/116958550-e76ce780-ac4f-11eb-850b-32c535965f04.png">
Bottom nav obscuring content
<img width="304" alt="3" src="https://user-images.githubusercontent.com/60120929/116958554-ea67d800-ac4f-11eb-9f47-7c6af95a0586.png">

**Comment by ky28059** [comment]
Oh, I'd also like to put here that currently, mobile users cannot sign in as the [more] tab has not been implemented yet.

**Comment by ky28059** [comment]
There's still one task remaining for responsive design.
Also, bootstrap modals don't let people scroll which is an issue on mobile as certain clubs' modals exceed the screen size.

**Comment by ky28059** [comment]
And events is still nonideal on mobile
![image](https://user-images.githubusercontent.com/60120929/128787145-5e0c7a9b-de48-4d6f-910a-3b396c07c11c.png)

**Comment by ky28059** [comment]
<img src="https://user-images.githubusercontent.com/60120929/129428072-f0600a2b-20c5-4912-b0b4-46de791fb025.PNG" width="250px"> <img src="https://user-images.githubusercontent.com/60120929/129428074-6849cf32-afbd-46d2-8227-25432b6d8708.PNG" width="250px"> <img src="https://user-images.githubusercontent.com/60120929/129428078-14021254-3f42-4607-965a-6268761a8b85.PNG" width="250px">

A note that the white stripes are coming from the parallax'd red background, but unsure how to make it more ergonomic. This seems to be a problem specific to old phones as Yu-ting's iPhone 8 has the parallax running fine.

**Comment by SheepTester** [comment]
Strange! Do you think the transform: translateZ(0); trick could help?

**Comment by ky28059** [comment]
Forgot to mention this earlier, but the changing of `position: absolute` to `position: fixed` in https://github.com/GunnWATT/watt/commit/cd81eefc1de4efa71017c45041927a641c18b8ac made rendering much much smoother on phones. Shall mark the white stripes task as done for now unless someone else is still having that problem on the latest version.

**Comment by ky28059** [comment]
I probably should have done this a while ago but the stacked tabs aren't that big of an issue (or at least, there isn't really a clean alternative immediately available imo). Closing this for now.
