### ISSUE TITLE
Please add NAHS art club to the Gunn club spreadsheet

### ISSUE THREAD

**Issue by zimranhomesuite** [GunnWATT/watt#143]
Hi,
I am Jenna, a Gunn student, using my father's account. 

The NAHS art club is missing from this spreadsheet:
https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vQ-UXugiZ8GznB367cO8JptTO9BLm5OE4D3WO8oZvYk_365lY25Q6eAFNSEIC5DGXGWOXwK_wauoTFT/pubhtml
Could you guys add it? 

It's a returning club, its name is Gunn National Art Honors Society Club,and it's a Tier 2 club. The blurb is as follows:
NAHS is a club held during Tuesday lunches. We organize projects that allow members to explore different mediums.
It is held on Tuesday lunches. It is in M-3, the art room. The club teacher advisor is Anita Su, and her email address is asu@pausd.org . Thank you for your help.

Best,
Jenna

**Comment by julia7hk** [comment]
Hi Jenna,
The spreadsheet is not maintained by WATT and is instead managed by SEC (that's Gunn's Student Executive Council, they deal with club-related issues and more). WATT simply scrapes the spreadsheet to get our school's club data.
As for NAHS not being on the spreadsheet, you guys are not an officially chartered club. I believe charter applications for the spring semester are open though so make sure to fill that out and you'll be on the spreadsheet!
