### ISSUE TITLE
Schoology graduation year is off

### ISSUE THREAD

**Issue by BubbyBabur** [GunnWATT/watt#15]
Around line 69 of `functions/functions/sgyauth.js` it seems that the fetched graduation year from Schoology is off (fetched 2023 for me, whereas should be 2024). Not quite sure why yet.

**Comment by SheepTester** [comment]
Is it possible it's using yu-ting's course data?

**Comment by ky28059** [comment]
No, I think it's schoology's internals being a year off. I remember seeing back when CC was in its infancy and it just pasted the JSON stringified schoology data in the page that my graduation year was listed as 2022. I'll try and find a discord message link.

**Comment by ky28059** [comment]
https://discord.com/channels/710932856251351111/710936824121655396/829069203772014662
Grad year listed as 2022 for me ¯\_(ツ)_/¯

**Comment by BubbyBabur** [comment]
I guess we can just offset the grad year by 1, though I don't know how consistent this issue is. Is it 1 year off for everyone?

**Comment by ky28059** [comment]
Could conduct some tests to be sure but I'm pretty sure its 1 off for everyone. I'll close this issue for now.
