### ISSUE TITLE
Dark mode issues

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#16]
Design bugs regarding dark mode (not a comprehensive list):

- [x] Electron images look bad as they were designed transparently for light backgrounds
- [x] `settings/periods` inputs look bad
- [x] Dark mode period colors need work
- [x] Sidebar active contrast
- [x] Button colors in club/staff components

**Comment by BubbyBabur** [comment]
<img width="355" alt="Screen Shot 2021-05-13 at 3 13 56 PM" src="https://user-images.githubusercontent.com/49625913/118194187-d7969580-b3fd-11eb-9854-41b0434cec5a.png">
Highlight color is ugly, but isn't a big deal in the end.

**Comment by BubbyBabur** [comment]
<img width="174" alt="Screen Shot 2021-05-13 at 3 15 02 PM" src="https://user-images.githubusercontent.com/49625913/118194304-feed6280-b3fd-11eb-87de-8ecf8953f29f.png">
Should add more contrast on the text for the selected category.

**Comment by BubbyBabur** [comment]
<img width="344" alt="Screen Shot 2021-05-13 at 3 15 40 PM" src="https://user-images.githubusercontent.com/49625913/118194347-162c5000-b3fe-11eb-934a-58fc2537cad2.png">
Don't know if it's intentional, but maybe turn the search bar into dark mode. Unsure about how user experience would be using a dark mode search-bar would be though.

**Comment by BubbyBabur** [comment]
<img width="529" alt="Screen Shot 2021-05-13 at 3 16 56 PM" src="https://user-images.githubusercontent.com/49625913/118194457-4247d100-b3fe-11eb-9ff5-c1bc2a8c193c.png">
More contrast on the "Add to My List" and "Close" buttons for viewing clubs/teachers.

**Comment by BubbyBabur** [comment]
<img width="176" alt="Screen Shot 2021-05-13 at 3 18 09 PM" src="https://user-images.githubusercontent.com/49625913/118194560-6e635200-b3fe-11eb-9d3f-f03199fb2808.png">
I'm not sure how I feel about the Watt logo's current color against a dark background. It might need more contrast?

**Comment by SheepTester** [comment]
> Unsure about how user experience using a dark mode search-bar would be though.

Discord has a search bar in dark mode, so it should be fine

![image](https://user-images.githubusercontent.com/22133785/118203631-4d582c80-b411-11eb-8e01-dccacd863b65.png)

**Comment by ky28059** [comment]
Mm, the search bar is explicitly set to white because the default dark on the red background looked a bit funky. Could perhaps see if you disagree by commenting out these two lines in `_search,scss`
```css
  background-color: white;
  color: black;
```

**Comment by ky28059** [comment]
Forgot that this was finished... whoops!
