### ISSUE TITLE
Primary colored radio buttons

### ISSUE THREAD

**Issue by saumyasinghal747** [GunnWATT/watt#18]
Currently, your radio buttons look like this:
![image](https://user-images.githubusercontent.com/65318685/118386278-31988600-b5cb-11eb-94e8-d85c44e59f25.png)

Change the color of the radio buttons to your primary color. 
1. Use the custom input component from here. https://reactstrap.github.io/components/form/#Custom-Inputs
2. Use inspect element to determine how to override the colors for these - you switched components because browser radios are unstylable, unlike these. As me if you need help with this - I've done it for ymath before.

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/129431727-5517deb2-abc5-460f-9ebb-2610c1ce1d82.png)
the radio button acts a bit strange when using the space key
