### ISSUE TITLE
Sticky events header

### ISSUE THREAD

**Issue by saumyasinghal747** [GunnWATT/watt#19]
Right now, scrolling through events, we forget that they are events.
![image](https://user-images.githubusercontent.com/65318685/118412478-11120f80-b64f-11eb-9eb2-0341a4ccff97.png)
Add this to your HTML:
![image](https://user-images.githubusercontent.com/65318685/118412600-bdec8c80-b64f-11eb-97be-7854d095a221.png)

(These are Bootstrap utility classes that come included with reactstrap, so use them!)

**Comment by saumyasinghal747** [comment]
In fact, instead of the `style` on your `<hr/>`, you can use

```html
<hr class="mb-0"/>
```

**Comment by ky28059** [comment]
Would this work?
<img width="252" alt="events" src="https://user-images.githubusercontent.com/60120929/118416449-994edf80-b664-11eb-9046-e0761f623597.png">

**Comment by ky28059** [comment]
^ That is using a div with `height: 100%` and `overflow: scroll`

**Comment by ky28059** [comment]
Hmm, perhaps your version is better. I'll see.

**Comment by ky28059** [comment]
Not sure about no margin <hr>, but the rest should be implemented.

**Comment by saumyasinghal747** [comment]
Removing the margin on `<hr/>` would probably make things easier to look
at, but your choice in the end. I have provided detailed info on how to do
that :)
