### ISSUE TITLE
Image Optimization

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#22]
The large electron images are having a large impact on cache size. Perhaps something like https://www.npmjs.com/package/react-optimized-image can be used for optimization?

**Comment by ky28059** [comment]
Closed for now via a manual squishing of image files. An automated plugin would be nice, but all options I looked into seemed really scary to implement. https://www.npmjs.com/package/react-optimized-image doesn't have great documentation, but neither does https://webpack.js.org/plugins/image-minimizer-webpack-plugin/. Both would require a override of CRA's default `webpack.config.js`, which is scary (see [this CRA issue](https://github.com/facebook/create-react-app/issues/10307)) and requires either another library ([most of which](https://github.com/timarney/react-app-rewired) are also deprecated due to CRA 2.0) or an eject.

**Comment by SheepTester** [comment]
For reference, while I manually compressed each image file for UGWA (because there weren't that many), I did make a [script to compress a bunch of images](https://github.com/SheepTester/sheeptester.github.io/blob/master/img/compress.js) for my personal website
