### ISSUE TITLE
Users have outdated version of WATT due to browser cache

### ISSUE THREAD

**Issue by ImNotRog** [GunnWATT/watt#24]
Many users are stuck with the old WATT version (sometimes without a working schedule) due to browser caching, which is clearly unideal.

This may also be a problem with future changes, as it might hinder deployment.

I suggest triggering a force refresh or something of the sort when WATT detects it is out of date, probably by checking a firestore field, which should be unaffected by browser caching.

**Comment by ky28059** [comment]
I don't think firestore is necessary for this. See https://github.com/dfabulich/service-worker-refresh-sample/blob/master/index.html for an example of service worker refreshing; I think you can see whether new changes are available through event listeners on `navigator.serviceWorker`. IMO I still think an alert telling users to refresh would be better than having it refresh automatically, but both seem doable.

**Comment by ImNotRog** [comment]
> IMO I still think an alert telling users to refresh would be better than having it refresh automatically, but both seem doable.

This would require a force refresh. Would you attempt to describe to the user how to force refresh, or would you have a button that force refreshed on click?

**Comment by SheepTester** [comment]
> > IMO I still think an alert telling users to refresh would be better than having it refresh automatically, but both seem doable.
> 
> This would require a force refresh. Would you attempt to describe to the user how to force refresh, or would you have a button that force refreshed on click?

It wouldn't; you'd just need to close the tab (redirecting out of scope seems to work) and then return back

**Comment by ImNotRog** [comment]
So would the user have to do that, or would this happen automatically on click?

**Comment by SheepTester** [comment]
Maybe you can do it automatically (w/o user consent 😳) if the user hasn't interacted with the web page yet, and if the user has, then show the message and do the fancy redirection on clicking "update" perhaps
