### ISSUE TITLE
Electron mascot images for no school days (moving the list from discord to here)

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#3]
### Geo:
- [ ] Shapes
- [ ] Proofs?
- [ ] Trig functions (acute)
### Trig:
- [ ] Unit circle
- [ ] Trig identities
- [ ] Sinusoids
### Analysis:
- [ ] Choose numbers / triangles?
- [x] Cardioids / limacons
- [ ] Lemniscates
- [ ] Matrices / transition diagrams
- [ ] 3D graphing
- [x] Bloch sphere and qubits
- [ ] GAtM (dihedral flip groups)
### Calc: [Undefined Behavior]
- [ ] Disc and washer methods

### Bio:
- [ ] Punnett squares / dihybrid crosses
- [ ] DNA polymerase
- [x] Cells
- [x] Cell cycle (Mitosis)
- [x] Pedigrees
- [ ] Food web
### Chem:
- [X] VSEPR
- [x] Hybridization
- [X] Electron config
- [X] Phase change /  Q = mCdeltaT?
- [X] Dipoles / IMFs?
- [x] Ideal gas law [wip]
- [x] Heat of reaction / activation energy?
### Physics:
- [ ] Projectile motion
- [ ] Free body diagrams
- [ ] Circular motion
- [ ] Collision / momentum
- [ ] Work energy / LOL diagrams
- [ ] Simple harmonic motion / springs / pendulums

## English:
- [ ] Reading a book?

### APUSH:
- [ ] George Washington
### Econ: [Undefined Behavior]
[Whatever Sean's drawing]

## Languages:
- [ ] Google Translate?
- [ ] Duolingo?
- [ ] French
  
### Orchestra:
- [x] Violin?
- [ ] Cello?
### Band:
- [X] Trumpet
- [ ] Drums?

### APCSP: [Undefined Behavior]
- [ ] Scratch?
### FOOP:
- [ ] Coding in Scheme [wip]
### APCS:
- [x] Box-and-pointer diagrams [wip]
- [ ] Sorting algos? (heapsort)
- [ ] Comparable Cows? [wip - comparable sheep]
- [x] Binary search trees?

## Autre:
- [X] Doing HW
- [X] Drinking coffee
- [X] Checking laptop [remove?]
- [ ] Texting? [wip]
- [ ] Checking WATT?

## GRT:
- [ ] Building the robot
- [x] Drawing sheet
- [ ] Ball bearing joiner?
- [ ] NEO motor?

### Winter Break:
- [ ] Skiing
### Summer Break:
- [ ] Beach?

**Comment by penguin212** [comment]
The images don't really work on dark mode.
![maxresdefault](https://user-images.githubusercontent.com/85318362/120716586-19ee4800-c47b-11eb-89b9-e7b5c7136a7a.png)
![Screenshot 2021-06-03 145022](https://user-images.githubusercontent.com/85318362/120716604-1eb2fc00-c47b-11eb-91fa-756e58b88162.png)
Maybe get separate images for dark mode with using a white pencil on a black background, or make the images with transparency.

**Comment by SheepTester** [comment]
Re dark mode,

`filter: invert(1);`: 
<img src="https://user-images.githubusercontent.com/22133785/120723423-90447780-c486-11eb-98e3-7c7149edf965.png" width="478" alt="Pressure image with filter: invert(1)">

`filter: invert(1) hue-rotate(180deg);`: 
<img src="https://user-images.githubusercontent.com/22133785/120723463-a3574780-c486-11eb-9c4b-3925798ca7df.png" width="464" alt="Pressure image with filter: invert(1) hue-rotate(180deg)">

**Comment by ky28059** [comment]
Yeah, this is mentioned in #16. I'm not sure a full invert of everything is fully desirable either though. Will think about this over summer probably.

**Comment by ky28059** [comment]
Some electron images do look a little weird inverted, but I suppose it's better than black. Will commit for now.
![image](https://user-images.githubusercontent.com/60120929/120878796-9bc19c80-c573-11eb-8732-f649c8568f2c.png)

**Comment by ky28059** [comment]
👴 🥰
