### ISSUE TITLE
Class links unnecessary

### ISSUE THREAD

**Issue by MysticalApple** [GunnWATT/watt#38]
You can set zoom links for specific classes in /settings/periods but Gunn has already returned to in-person school. Perhaps replace with room numbers or something similar?

**Comment by SheepTester** [comment]
Allowing links to the Schoology materials page would probably be nice. iirc I got a suggestion for allowing multiple links last year; I'll try to find it to see what their other use case was

**Comment by ky28059** [comment]
Yeah, maybe we can just rebrand them to be schoology links. It's not like the functionality depends on what type of links they are, just that they're valid urls.

**Comment by MysticalApple** [comment]
Having schoology links on watt would be pretty useful

**Comment by ky28059** [comment]
Shall close this as zoom links have been rebranded to simply "links"
