### ISSUE TITLE
Bottom nav issues

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#40]
Related to #13. 
The bottom nav covers the bottom part of the screen, and when scrolling on mobile two scrollbars are visible.

<img src="https://user-images.githubusercontent.com/60120929/130175723-41426f2f-1bcb-49e7-aff4-f79ef715713c.PNG" width="300"> <img src="https://user-images.githubusercontent.com/60120929/130175725-4e1eb761-4fa7-43ed-9f0a-7df4bd9618da.PNG" width="300">

**Comment by SheepTester** [comment]
Oops, I might've introduced this via #32 because I made the navbar `position: fixed;`, but I believe I also added padding to the bottom of the content for mobile screens. I'm not able to reproduce this on Android, so I think this is an iOS Safari bug

**Comment by SheepTester** [comment]
Ah, the horizontal scroll bar is because the Zoom link on 2021-08-19 has a long string of text with no spaces, so it can't wrap, and it extends past the edge of the screen. The navbar doesn't cover up the bottom edge of the screen for me though

**Comment by ky28059** [comment]
<img src="https://user-images.githubusercontent.com/60120929/130529994-0eff9dea-0bc3-4ebe-90f7-5a9500f10b8e.png" width="300px">
Yeah, on chrome the padding works properly, but on my phone it just doesn't. How strange!

**Comment by ky28059** [comment]
![image](https://user-images.githubusercontent.com/60120929/130530597-a0236c24-cb3e-4125-90c5-c4ba880029b9.png)
I will also say that sometimes upon opening inspect the layout gets screwed.

**Comment by ky28059** [comment]
I'll convert this into a separate issue.

**Comment by ky28059** [comment]
Seems like this was a flex problem and was fixed in the PR.

**Comment by SheepTester** [comment]
Oh nice, two birds with one stone!
