### ISSUE TITLE
SVG sometimes doesn’t render upper two waves on mobile

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#52]
<img src="https://user-images.githubusercontent.com/60120929/132448620-4ed86675-9a6d-4ae2-b8c5-fa0a7f07ecd5.png" width="300px"> <img src="https://user-images.githubusercontent.com/60120929/132448626-ed6eeab8-a707-4105-a2d3-771c9ca5a04e.png" width="300px">
Or perhaps more accurately it uses the top wave’s color for the bottom two as well; no clue what triggers this, I encountered this merely by leaving watt open for a few minutes.

**Comment by ky28059** [comment]
@SheepTester any idea why this occurs?

**Comment by SheepTester** [comment]
Is this an iOS bug

**Comment by ky28059** [comment]
Perhaps it is related to scrolling; on Michael’s phone it has been reproduced by going to a different tab to refresh the svg and then going back to schedule and scrolling down.

**Comment by ky28059** [comment]
It might also have something to do with repainting; changing the theme on another device causes this bug to happen on phone when the color scheme switches.
