### ISSUE TITLE
Misspelling in a name in "Staff" tab

### ISSUE THREAD

**Issue by Incog99** [GunnWATT/watt#54]
Under Tom Casavant it says "Long Tem Sub" instead of Long Term Sub

**Comment by ky28059** [comment]
This is due to Gunn's website being terrible with spelling, but maybe @ImNotRog can manually fix?

**Comment by SheepTester** [comment]
I'm not sure. How can a student know more than the school? The Gunn website proports to have the most accurate and up-to-date information; we may not want to provide inaccurate information by contradicting the school. It would be disrespectful to taint the staff directory with ill-advised student-made "corrections"

**Comment by ImNotRog** [comment]
Fixed; It was actually a misspelling on Parentsquare. Gunn's resources are absolute anarchy, I tell you.
