### ISSUE TITLE
Mobile display

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#6]
Perhaps using https://www.npmjs.com/package/react-responsive as @SheepTester suggested

**Comment by SheepTester** [comment]
Just watch Ben Awad's video:

[![youtube thumbnail](https://img.youtube.com/vi/Dk1gxZ_K3E0/hqdefault.jpg)](https://www.youtube.com/watch?v=Dk1gxZ_K3E0&t=75s)

**Comment by ky28059** [comment]
Perhaps, but would need to write code on top of watching the video too

**Comment by SheepTester** [comment]
but it is very simple writing code because it is mere copypaste hippity hoppity
