### ISSUE TITLE
Classes sidebar for mobile

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#80]
Keeping the circle sidebar on mobile leads to a squished and bad design, but something else needs to be implemented to allow mobile users to change classes. Compare:

<img src="https://user-images.githubusercontent.com/60120929/147843332-81c75627-09eb-4cf4-8264-178a09a68b5d.png" height="600px"> <img src="https://user-images.githubusercontent.com/60120929/147843327-428a0f4c-5ee7-4fca-9eae-2466669c5e7f.png" height="600px">

**Comment by ImNotRog** [comment]
Entirely agree with the above. Mobile looks way better without sidebar.
