### ISSUE TITLE
Date picker issue with April 1

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#85]
Steps to reproduce: go to April 1st on the date picker and click the left arrow. Instead of displaying March 31, it displays March 1. This seems to happen only for April 1. Is this an out of season April fools joke?

**Comment by SheepTester** [comment]
When's daylight savings?

**Comment by ky28059** [comment]
March 13, so probably not the reason?

**Comment by ky28059** [comment]
Alternate steps to reproduce:
Go to April 1st on the datepicker and then click March 31st. It will first go to March 1st.

**Comment by ky28059** [comment]
Even stranger, this glitch exists for any day in the months of April and June, but not May.

**Comment by ky28059** [comment]
Oh, I see what's going on here. When a day from a 30-day month attempts to set its day to 31, it overflows to 1 (this is why the glitch exists for February but redirects to March 3 instead of 1).

**Comment by ky28059** [comment]
Closed in https://github.com/GunnWATT/watt/commit/1e4764a72fd93addbb3f1392840f0cdfa4d2e2b5
