### ISSUE TITLE
Schoology Integration (beyond just assignments and grades)

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#9]
Saumya's CC (formerly HC) has some interesting schoology ideas I think are worthy of implementation, WATT could consider having:

- Schoology message integration (as a way to check messages from teachers while also replacing ugwa's interstudent communication)
- Updates and materials
- Assignment submission
- Setting period name and zoom link to fetched defaults

**Comment by saumyasinghal747** [comment]
Let me know if you want to use the Imperichat API/SSE for interstudent communication. It is only the UI that was sucky. Also, I'm curious what you have in mind for fetching zoom links - are you just going to spam item names for the word "zoom"? 

P. S. CC is not a HC replacement. CC can be said to be HC's more successful younger sibling. 😄

**Comment by ky28059** [comment]
> Let me know if you want to use the Imperichat API/SSE for interstudent communication. It is only the UI that was sucky. Also, I'm curious what you have in mind for fetching zoom links - are you just going to spam item names for the word "zoom"?
> 
> P. S. CC is not a HC replacement. CC can be said to be HC's more successful younger sibling. 😄

There is an already implemented function to fetch zoom links, you can see the raw output by going to /super-secret-testing and clicking the button
