### ISSUE TITLE
Failed firestore write on schoology reset

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#94]
Same issue as mentioned a month ago in  https://discordapp.com/channels/795043639214604370/796534035874447360/960309922829045830. Resetting schoology and clicking the confirmation button fires a firestore write with `options.sgy` set to true, but when resetting `options.sgy` is already true in the firestore userData and this write is blocked by the stricter firestore rules implemented after The Incident, causing the button to be unresponsive.

![image](https://user-images.githubusercontent.com/60120929/167279330-38e9baa3-96fb-4f4f-b45a-9345e0a32cd0.png)

The firestore rules in question. A potential fix is to only attempt a firestore write if `options.sgy` is false, though I'm unsure if that would break something else.

![image](https://user-images.githubusercontent.com/60120929/167279233-35097da6-2232-4cb2-b09d-e489905b0f53.png)
(from @124274sashimi)

**Comment by ImNotRog** [comment]
I would fix it, but it seems that Schoology authentication is completely down at the moment. Seems to be the recurring problem of Schoology not recognizing oauth_callback as a callback URL.

**Comment by ky28059** [comment]
Closed in https://github.com/GunnWATT/watt/commit/7f0f8436e18ead1df201795e58ecfb1ce98cb416? A more elegant fix may exist but until then this solves the problem.
