### ISSUE TITLE
Article pages

### ISSUE THREAD

**Issue by ky28059** [GunnWATT/watt#98]
Formerly, `/utilities/articles` would link to article pages hosted at `/articles/page` (top image). I generally like the choice of replacing the pages with modals instead (bottom image) but should the `/articles/page` pages stick around? A use-case for them would be if someone wants to send a quick link to a specific article they can do so easily by linking `gunn.app/articles/...`, but if this feature isn't deemed useful then the extra pages would just sit around and increase bundle size.

Thoughts?

![image](https://user-images.githubusercontent.com/60120929/178624311-b800b092-acca-49fa-9ac5-d6908748314d.png)
![image](https://user-images.githubusercontent.com/60120929/178624337-44d5b6f9-4ab3-4a47-82b3-5cd9137ba57a.png)

**Comment by saumyasinghal747** [comment]
I think they should be pages on mobile but modals on desktop to take advantage of the large screen space.

**Comment by icedTet** [comment]
Regarding bundle sizes, can't you just use React.lazy for those pages specifically?
